### ISSUE TITLE
Trying web ar rocks hand for wrist watch VTO/rings VTO

### ISSUE THREAD

**Issue by Juanmaramon** [WebAR-rocks/WebAR.rocks.hand#1]
Hi @xavierjs ,

I'm trying web ar rocks hand for wrist watch or rings VTO. But as far as I see included demos only track face palm side and not dorsal side of the hand.

![palm](https://user-images.githubusercontent.com/2853271/94440993-830e1500-01a2-11eb-95af-46ba3adff175.png)
![dorsal](https://user-images.githubusercontent.com/2853271/94441013-886b5f80-01a2-11eb-9e93-a1c1d69c836d.png)

I'm using NN_OBJMANIP_3.json neural network for testing.

Is there something I missing?

Thanks!

**Comment by xavierjs** [comment]
Hi @Juanmaramon 

Wrist and Ring VTO will be available from January 2021, I have sold the exclusivity of the tech to another company for this delay.

Best regards,
Xavier
