### ISSUE TITLE
Train custom model

### ISSUE THREAD

**Issue by ShakhzodbekYuldoshov** [WebAR-rocks/WebAR.rocks.hand#27]
I want to train my own custom model for wrist detection? How can I do it? What models could be used instead of .json neural networks that you provided

**Comment by xavierjs** [comment]
You cannot, the training part is not released and my tech is not compatible with mainstream DL engines.

**Comment by diogomaximo** [comment]
Hi @xavierjs 
Taking advantage of the thread.
Which framework did you use to train this model (feet and shoes) that generates this json?
Can we train a model with more options of feet and shoes?

**Comment by xavierjs** [comment]
Hi @diogomaximo 
I use my framework, which is not publicly released.

**Comment by diogomaximo** [comment]
Hi @xavierjs,
Thanks for the quick response.
Do you intend to publish this framework or even train more foot models?

**Comment by xavierjs** [comment]
Hi @diogomaximo 
It is not on my roadmap; it would take me too long to provide support, write tutorials, etc. Some things inside are patentable but not patented.
